### PR TITLE
chat: image UX enhancements

### PR DESCRIPTION
**Pull request by tomholford**
# Context

Resolves several open issues regarding image UX in chat

# Changes

- [x] #1425 
- [x] #1509 
- [x] #1512 

# Preview

## Paste Single or Multiple to Upload with Caption

https://user-images.githubusercontent.com/16504501/208105471-c3d2ead4-1f94-4dbf-a9cb-4250fcc28e4f.mp4

## Drag and Drop

https://user-images.githubusercontent.com/16504501/208116734-660fbc18-40db-45d9-ac93-b38e0fa90ef5.mp4

## Click X to Remove

https://user-images.githubusercontent.com/16504501/208122484-19a783c7-63eb-4cb5-83b4-e00e2ab19d48.mp4

### CODE REVIEW

**Review by urcades — CHANGES_REQUESTED** [review]
Oh man this is incredible @tomholford – the only minor change I’d suggest here is editing the label text in the input field to “images” from “references”, so that the label matches the content correctly, otherwise this is looking beautiful and I am so excited to use this.

**Comment by jamesacklin** [comment]
Agreed, incredible. Two quick things:
- Can you add `.object-cover` to the image thumbnails to avoid squishing?
- We'll need some kind of indicative state (maybe a strong blue border) for the drop target while `isDragging`. People can learn this behavior but first-timers will need help discovering it.

**Comment by tomholford** [comment]
> Oh man this is incredible @tomholford – the only minor change I’d suggest here is editing the label text in the input field to “images” from “references”, (as in `Attached: 2 images`) so that the label matches the content correctly, otherwise this is looking beautiful and I am so excited to use this.

Thanks Ed! Okay will do. It's possible to post multiple types of references at once, e.g. an image and a chat message reference. What should the copy say in this case?

**Comment by patosullivan** [comment]
This looks awesome, but I did notice that if I paste an image link rather than pasting the image directly the image still shows up as full size in the chat scroller.

**Comment by patosullivan** [comment]
Example:
image

The first image was a link, the second was just a paste. Same image.

**Comment by tomholford** [comment]
> This looks awesome, but I did notice that if I paste an image link rather than pasting the image directly the image still shows up as full size in the chat scroller.

Thanks for the feedback, what is the expected behavior?

**Comment by jamesacklin** [comment]
I think we want the smaller size for image links. We can follow up with another bug, I think?

**Comment by vcavallo** [comment]
beautiful! very excited for this.

**Comment by jamesacklin** [comment]
@tomholford If you update the screencaps, we can get a re-review from @urcades and we'll be good to go

**Review by patosullivan — APPROVED** [review]

**Comment by urcades** [comment]
> Agreed, incredible. Two quick things:
> 
> * Can you add `.object-cover` to the image thumbnails to avoid squishing?
> * We'll need some kind of indicative state (maybe a strong blue border) for the drop target while `isDragging`. People can learn this behavior but first-timers will need help discovering it.

Very good catch – I didn't see the images were being squished in the mobile preview of the video.

> Thanks Ed! Okay will do. It's possible to post multiple types of references at once, e.g. an image and a chat message reference. What should the copy say in this case?
> 
> edit: we discussed out of band in the standup, going to show 'Images' if all attachments are images, otherwise fallback to 'References'

I think this is a fine solve, but after thinking about it for a bit, I think we could very well generalize the label copy to simply 'attachments', no need to distinguish between media types:

attachments

The proposed repositioning of the "Attachment" status bar to the top of the input is a nod to some future ideas we have behind placing a replies-signifying interface in that status bar as well.

**Pull request merged**
