### PR TITLE
mobile: hide keyboard on scroll in chat scroller

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes LAND-921 by creating the ref in the parent component for chat channels, DMs, multi DMs, and then passing the ref into the scroller and input in each case and tracking whether or not we're scrolling to determine when we should blur the input.

https://github.com/tloncorp/landscape-apps/assets/1221094/57441dba-5ded-4fa9-8293-f5dd0cdf2abb

### CODE REVIEW

**Review by arthyn — APPROVED** [review]
lgtm

**Comment by latter-bolden** [comment]
code looks good, but is this working for you guys on device? Doesn't seem to be for me

**Comment by patosullivan** [comment]
> code looks good, but is this working for you guys on device? Doesn't seem to be for me

I tested in the simulator. I can test on my Android device in the morning, though.

**Comment by jamesacklin** [comment]
Also not seeing this on-device:

https://github.com/tloncorp/landscape-apps/assets/748181/c651d261-bc7a-427a-aed8-db760ac00e3e

**Comment by patosullivan** [comment]
@latter-bolden @jamesacklin can you guys try now?

**Comment by jamesacklin** [comment]
This works for me now! Just some conflicts and we're g2g.

**Review by jamesacklin — APPROVED** [review]

**Pull request merged**
