### PR TITLE
clubs: only accept once

### LINKED ISSUE #1565: talk: need to repeatedly accept group dm `invite`
image

`%talk` hash `0vc.9kn8n.68vo6.v4e7g.4mou1.ekqeg.65ttj.avtlg.02t5l.dts7e.qjfk1` still asking me to accept same group DM roughly every time I open it. This was resolved for a day or so and then re-occurred.

### PR DESCRIPTION
**Pull request by arthyn**
This fixes #1565 by ensuring that we hear facts about club's membership and meta even if we haven't visited said club and also by loading all clubs initially so that we can reconcile with whatever is stored in local storage.

This does change our subscriptions so this needs to be communicated with external parties.

Also threw in a fix for the issue of channels on refresh not loading, some console errors about nested buttons with chat reactions, and the issue with media query listeners disappearing #1529.

### CODE REVIEW

**Review by patosullivan — APPROVED** [review]
Looks great, works well locally.

**Comment by tomholford** [comment]
>  some console errors about nested buttons with chat reactions

thank you! this was rather obnoxious

**Review by tomholford — APPROVED** [review]
This is great! Addresses some annoyances, and unifies the implementation and is thus more maintainable. LGTM

**Comment by jamesacklin** [comment]
Very nice. Do we need state migrations for this?

**Comment by arthyn** [comment]
no state migrations needed, but at the very least @alecananian will likely need to change his subscription for club meta updates

**Pull request merged**
