### PR TITLE
chat: mentions

### PR DESCRIPTION
**Pull request by arthyn**
This addresses #68, #69, #70 however it does not do any kind of weighting of results, just basic fuzzy match like ship selector.

### CODE REVIEW

**Comment by jamesacklin** [comment]
Mentions work in Chat (as the PR explicitly says) but fail in the following ways:

**Heap curios:**
image
```
Urbit.ts:254 gall: poke-as cast fail :heap [a=%json b=%heap-action-0]
[%bad-key 'ship']
/lib/heap-json/hoon:<[238 5].[254 7]>
/lib/heap-json/hoon:<[237 5].[254 7]>
/lib/heap-json/hoon:<[236 5].[254 7]>
/lib/heap-json/hoon:<[235 5].[254 7]>
[%key 'content']
[%key 'add']
[%key 'delta']
[%key 'curios']
/lib/heap-json/hoon:<[193 12].[193 40]>
/lib/heap-json/hoon:<[193 5].[193 41]>
/lib/heap-json/hoon:<[192 5].[193 41]>
/lib/heap-json/hoon:<[191 5].[193 41]>
[%key 'update']
/sys/vane/clay/hoon:<[832 51].[832 63]>
/sys/vane/gall/hoon:<[1.040 27].[1.040 45]>
```

**Curio quips:**
image
```
react_devtools_backend.js:4026 gall: poke-as cast fail :heap [a=%json b=%heap-action-0]
[%bad-key 'ship']
/lib/heap-json/hoon:<[238 5].[254 7]>
/lib/heap-json/hoon:<[237 5].[254 7]>
/lib/heap-json/hoon:<[236 5].[254 7]>
/lib/heap-json/hoon:<[235 5].[254 7]>
[%key 'content']
[%key 'add']
[%key 'delta']
[%key 'curios']
/lib/heap-json/hoon:<[193 12].[193 40]>
/lib/heap-json/hoon:<[193 5].[193 41]>
/lib/heap-json/hoon:<[192 5].[193 41]>
/lib/heap-json/hoon:<[191 5].[193 41]>
[%key 'update']
/sys/vane/clay/hoon:<[832 51].[832 63]>
/sys/vane/gall/hoon:<[1.040 27].[1.040 45]>
```

**Diary quips:**
image
```
react_devtools_backend.js:4026 gall: poke-as cast fail :diary [a=%json b=%diary-action-0]
[%bad-key 'ship']
/lib/diary-json/hoon:<[465 5].[487 7]>
/lib/diary-json/hoon:<[464 5].[487 7]>
/lib/diary-json/hoon:<[463 5].[487 7]>
/lib/diary-json/hoon:<[462 5].[487 7]>
[%key 'inline']
[%key 'content']
[%key 'add']
[%key 'delta']
[%key 'quips']
[%key 'delta']
[%key 'notes']
/lib/diary-json/hoon:<[346 12].[346 40]>
/lib/diary-json/hoon:<[346 5].[346 41]>
/lib/diary-json/hoon:<[345 5].[346 41]>
/lib/diary-json/hoon:<[344 5].[346 41]>
[%key 'update']
/sys/vane/clay/hoon:<[832 51].[832 63]>
/sys/vane/gall/hoon:<[1.040 27].[1.040 45]>
```

@arthyn Thoughts on disabling the ~ hotkey in just these fields?

**Comment by jamesacklin** [comment]
Excellent, fix looks good.

**Review by jamesacklin — APPROVED** [review]

**Review by patosullivan — APPROVED** [review]
The chat.hoon changes compiled just fine and the mentions worked as expected in the JS app. This is awesome. The only issue I noticed is that if I see a mention on a ship that doesn't have a version of %groups that supports mentions yet I will see an error: `Encountered error:Unhandled message type: {"ship":"~finned-palmer"}`

Should we account for this? Seems like it's not a big deal since everyone *should* have mentions very soon anyway.

**Comment by jamesacklin** [comment]
Yeah, I'm willing to punt on that since it'll be an essential component soon

**Pull request merged**
