### PR TITLE
groups: retain scroll position through nav changes

### PR DESCRIPTION
**Pull request by dantish**
Fixes LAND-804

### CODE REVIEW

**Comment by patosullivan** [comment]
Looks good to me!

**Comment by arthyn** [comment]
it said `currentVirtuosoRef?.getState` is not a function

**Comment by dantish** [comment]
Probably it means that the version of the lib hasn’t been updated on your machine for some reason, maybe try to remove node_modules and install again?

**Comment by jamesacklin** [comment]
A note from standup: clearing .vite cache seems to work, as well as node_modules

**Review by arthyn — APPROVED** [review]
lgtm, let's play around with it and adjust if necessary

**Pull request merged**
