### PR TITLE
chat: sent/delivered status for messages

### PR DESCRIPTION
**Pull request by rcrdlbl**
partially covers #711 

**Functionality that is covered:**
- Optimistic posting of sent messages from input field to ChatScroller
- "Sent from Browser, not delivered to host ship" and "Delivered to host shop" now have distinct visual states.

The effect on UX is that messages now feel like they post instantly now instead of having a percieved lag as the message makes its roundtrip from the host ship back to your urbit. (this is still so much faster than g1, it sometimes feels instant! but often it still doesn't!)

**Functionality that needs to be covered:**
- The distinct intermediary state of "sent from browser to user's ship, not yet reached host ship" detailed in issue #711
- design: https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs-(Locked)?node-id=1292%3A69107

 @arthyn and i have determined that some sort of backend update is necessary for this to be achievable in any reasonable + reliable fashion, so we'd prefer to break open a second issue to get this feature finished up.

I feel pretty strongly that this visually minor feature should be put in before general release – it's actually incredibly informative on *why* a message didn't deliver instantly (no more going to the terminal to `|hi` a group's host when messages don't seem to deliver! And people who wouldn't think to do this can get the same information at a glance!)

### CODE REVIEW

**Comment by nerveharp** [comment]
👑, will test it out today

**Review by nerveharp — APPROVED** [review]
Feels really nice in situ, I encourage others to set their dev proxy to a live ship and test it out (~fabled-faster/interface-testing-facility is a real-enough case).

**Review by arthyn — APPROVED** [review]
lgtm with suggestions

**Review by liam-fitzgerald — APPROVED** [review]
Looks good! Ship it!

**Pull request merged**
