### PR TITLE
groups/channels: connection and saga visibility

### PR DESCRIPTION
**Pull request by arthyn**
This includes @jamesacklin 's previous work to add connection indicators everywhere in #2698. This PR adds on top of that to also include protocol compatibility checking and adds a few more places to check including the invite dialog and all channels list as well as anywhere that we perform actions on the group/channel.

Fixes LAND-532

### CODE REVIEW

**Comment by jamesacklin** [comment]
Checked this out locally (and committed the desk changes), connectivity indicators look good and function.

Is there a way I can bump a saga here or there to check out the disabled states?

**Review by patosullivan — CHANGES_REQUESTED** [review]
I don't see an issue with the code, but when trying to access a group hosted by another dev moon it never loads, just gets stuck in the loading state. It looks like it has something to do with an issue with the indexdb cache, I see this error before the group loading issue starts:

image

**Comment by arthyn** [comment]
You might have to commit the backend changes to the moon? unless you did that already. I know we see those messages when we try to cache an error response (which we should probably handle).

**Review by latter-bolden — CHANGES_REQUESTED** [review]
The JS changes look good to me. When stubbing the compatibility hooks, it works as expected. The only spot I found where I could still trigger updates was by modifying roles for members in the Admin Panel.

However, when I try to simulate an incompatibility by bumping the `okay` value on the group host, I'm unable to trigger the blocked inputs. RQ dev tools show the `saga` for the group as ahead, but when I log from the compatibility hooks, it shows up as synced. 

@arthyn were you able to successfully test this with a simulated mismatch during development?

**Comment by jamesacklin** [comment]
@latter-bolden Feel free to add interactivity blockers to:
- drag action in All Channels
- edit capabilities for each channel and creating/deleting channels in All Channels

The "Leave" should stay; you should be able to leave regardless of protocol version.

**Review by latter-bolden — APPROVED** [review]

**Pull request merged**
