### PR TITLE
groups: app info and group modals no longer scrollable; incorrect spacings

### PR DESCRIPTION
**Pull request by dantish**
Fixes LAND-666

### CODE REVIEW

**Comment by arthyn** [comment]
sorry I should have put more context on LAND-666 it was meant to be for https://github.com/tloncorp/landscape/blob/master/ui/src/components/AppInfo.tsx in Landscape

**Comment by dantish** [comment]
> sorry I should have put more context on LAND-666 it was meant to be for https://github.com/tloncorp/landscape/blob/master/ui/src/components/AppInfo.tsx in Landscape

Ooops....😅
Okay, let's fix it too👍

**Comment by dantish** [comment]
@arthyn seems like the app info modal is scrollable, can you reproduce it now?
https://github.com/tloncorp/landscape-apps/assets/22919953/62b38d25-8514-421c-a387-185df551a95e

**Comment by arthyn** [comment]
@dantish ah sorry again haha, it's only through search apparently! if you click get urbit apps and then click get on one of the apps you don't have you should see.

**Pull request merged**
