### PR TITLE
chore: set up npm workspaces with shared package

### PR DESCRIPTION
**Pull request by alecananian**
PR Checklist
- [ ] Includes changes to desk files
- [X] Describes how you tested the PR locally (test ship vs livenet)
- [ ] If a new feature, includes automated tests
- [ ] Comments added anywhere logic may be confusing without context

Changes
- Updates repository to use npm workspaces
- Creates shared package at `packages/shared` with sample shared type to start
- Updates the web UI's group state manager to use the example shared type
- Moves Tlon mobile app into monorepo architecture at `apps/tlon-mobile` with bundle ID `io.tlon.groups.staging`

Tested with my livenet ship:
1. Delete all existing `node_modules` folders in your repo: `rm -rf ./**/node_modules`
2. Install dependencies at the root level: `npm i`
3. Follow setup directions in `apps/tlon-mobile/README.md`
4. Plug in your device or start the iOS simulator and run Tlon mobile: `npm run dev:ios`

No changes were made to the way the web UI is run for now

### CODE REVIEW

**Comment by alecananian** [comment]
Marking as draft because the rest of the CI workflows need updating. But the app package should be good for review.

**Comment by mrozanski** [comment]
For the new bundle ID, we should use a distinctive app icon so it's. not the same as tlon-mobile's currently in production.
I'll followup in Linear.

**Comment by alecananian** [comment]
Discussed with @mrozanski and @dnbrwstr, plan now is to move the `./ui` folder to `./apps/tlon-web` and leave the `./desk` folder at the root of the repo since it's not a workspace package. cc @arthyn @Fang- any issues with this folder structure/naming?

**Comment by arthyn** [comment]
@alecananian sounds good to me

**Comment by alecananian** [comment]
@mrozanski The web code is now in `apps/tlon-web` with the PR workflow passing

**Review by latter-bolden — APPROVED** [review]

**Review by mrozanski — APPROVED** [review]

**Pull request merged**
