### PR TITLE
chat: avoid giving useMessageEditor any deps that change on submit

### PR DESCRIPTION
**Pull request by arthyn**
OTT this should solve the most recent case of #1729

### CODE REVIEW

**Review by patosullivan — APPROVED** [review]
This looks good and runs well locally!

**Comment by patosullivan** [comment]
Looks like we still have one CI issue though.

**Comment by patosullivan** [comment]
I'm still losing focus on mobile :(

**Review by patosullivan — CHANGES_REQUESTED** [review]
The chat input focus issue seems to persist on mobile (at least on my Android phone).

**Comment by arthyn** [comment]
ok lemme check it out

**Comment by arthyn** [comment]
@patosullivan should work now

**Review by tomholford — APPROVED** [review]
LGTM

**Comment by patosullivan** [comment]
It's broken on desktop now for me:

https://user-images.githubusercontent.com/1221094/213582458-fbe1e8de-f3c8-4643-864d-9d1eee39ec0c.mov

**Comment by patosullivan** [comment]
Disregard the last comment (I was looking at groups while running the talk frontend), it works fine on desktop.

There is an issue with mobile losing focus and then regaining it, though. The keyboard disappears and then pops back up, it's pretty jarring.

**Review by patosullivan — CHANGES_REQUESTED** [review]
Need to figure out a different way to get focus back without triggering the keyboard to disappear and reappear on mobile.

**Comment by patosullivan** [comment]
https://user-images.githubusercontent.com/1221094/213583641-cfb48ed1-956a-4148-8355-17104d0b972b.mp4

Ignore cringe discord notifications pls

**Review by patosullivan — APPROVED** [review]
We can't repro the issue I'm seeing, we should probably merge for now and see if we can get a repro on another android phone internally.

**Pull request merged**
