### PR TITLE
talk: store ships in ship selector locally in NewDm

### LINKED ISSUE #1484: talk: switching pane/window while inputting message target clears input field
**Describe the bug, optionally with screenshots**
Go to 'New Message', enter some text in the 'Search for Urbit ID..' field, and then switch panes or windows and switch back.  The text will have been cleared, but the more intuitive behaviour is that it be preserved.

**Additional context:**
- Brave on macOS.

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes #1484

### CODE REVIEW

**Review by arthyn — APPROVED** [review]
lgtm

**Comment by tomholford** [comment]
Does this need to be unset on send / create of new DM?

**Review by tomholford — APPROVED** [review]
One question in the comments, otherwise LGTM

**Comment by patosullivan** [comment]
> Does this need to be unset on send / create of new DM?

good catch, yes.

**Pull request merged**
