### PR TITLE
refs: responsive byline elements

### LINKED ISSUE #1268: groups/mobile: broken text wraps in references

### PR DESCRIPTION
**Pull request by jamesacklin**
Uses container queries in refs to show or hide various elements in the reference bar to avoid the ugly wrapping seen in #1268. Introduces a container-query plugin for Tailwind, which meant upgrading Tailwind and removing the `prettier-plugin-tailwindcss` package.

Within the reference bar itself, we:
- use the xs avatar size everywhere
- show the group image next to the group name
- consolidate the group image + channel name at the smallest width
- hide the channel details when hovering to see the date at the smallest width

responsive-refs

Also responds nicely to the date-on-hover element in the author byline by hiding the channel context at small sizes:

responsive-refs-name-1

...or by truncating the author name at larger sizes:

responsive-refs-name-2

Fixes #1268

### CODE REVIEW

**Review by urcades — APPROVED** [review]
Oh hell yeah, these look excellent

**Review by arthyn — APPROVED** [review]
looks great! is the prettier package not needed any more with the updated tailwind or something?

**Comment by jamesacklin** [comment]
We load the eslint plugin from the @tloncorp eslint config anyway, so with eslint-prettier, it's redundant. The container queries plugin was causing Prettier to barf on this: https://github.com/tailwindlabs/tailwindcss/issues/4050

**Comment by jamesacklin** [comment]
Looks like @patosullivan's comment refs bork my ReferenceBar; WTAL.

**Pull request merged**
