### PR TITLE
channels: fix various cache issues, and then some.

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes LAND-1154
Fixes LAND-1156
Fixes LAND-1151
Fixes LAND-1152
Fixes LAND-1153

Also fixes issues with type names and comment ordering.

Most of this fell out from the changes around using page cursors from the backend in useInfinitePosts.

I also tried to simplify things a bit and remove some dead code. We could still stand to reduce some duplicate code, but this should fix all of the above issues for now.

Please pull it down and test against a ship running the `hm/hackweek` branch.

### CODE REVIEW

**Comment by patosullivan** [comment]
Fixes LAND-1157 as well.

**Review by jamesacklin — CHANGES_REQUESTED** [review]
Comments now behave as expected. I edited a note and got the expected fix for LAND-1161. All behave much more smoothly.

Two things:

- Editing a gallery item changes the item itself, but does not update the text in the index (gallery root view).
- Notebook notes still take 5-15 seconds to load even from the host, but I'll open a separate issue for that.

**Comment by patosullivan** [comment]
> Comments now behave as expected. I edited a note and got the expected fix for LAND-1161. All behave much more smoothly.
> 
> Two things:
> 
> * Editing a gallery item changes the item itself, but does not update the text in the index (gallery root view).
> * Notebook notes still take 5-15 seconds to load even from the host, but I'll open a separate issue for that.

I can't repro the gallery item issue. Maybe this is happening in a specific group?

**Comment by patosullivan** [comment]
I also can't repro the second issue, actually.

**Comment by mrozanski** [comment]
I can reproduce ["gallery: unable to edit blocks" ](https://linear.app/tlon/issue/LAND-1154/gallery-unable-to-edit-blocks) from a `hackweek` ship and the latest groups.

Now, to verify the fixes in this branch I'm stuck at trying to create a gallery channel locally (no https) 
new-channel-stuck

Is this expected?  Can I create a channel from this branch?

**Comment by jamesacklin** [comment]
@mrozanski's back-end was wrong -- his %groups version was still 4.8.1. Looking into why he's not getting updates from ~livdev-dozzod-marnus.

**Review by jamesacklin — APPROVED** [review]

**Comment by jamesacklin** [comment]
Was able to validate:
- Editing a gallery item does change the item itself _and_ the item in the gallery index.
- Loading a note does not take minutes.

**Pull request merged**
