### PR TITLE
notes: add proper storage and rendering for codeblocks

### LINKED ISSUE #1616: notebooks: Syntax highlighting not displayed within notebook codeblocks
**Describe the bug, optionally with screenshots**
When editing a notebook a bunch of newlines are added to the editor.

Also any meta stored in block comments get lost and the formatting gets all screwy

**To Reproduce**
1. Make a notebook entry that uses block quotes and multiple new lines
2. save it
3. edit it

**Expected behavior**
The formatting and meta data should be saved between saves

**Additional context:**
- planet
- Self Hosted
- Windows Chrome

### PR DESCRIPTION
**Pull request by patosullivan**
Still working on the wrapParagraphs issue, so I branched off of there (codeblock formatting would get messed up otherwise).

This should fix #1616 

I imagine we need to do some kind of state transition to account for the new key? cc: @arthyn

### CODE REVIEW

**Comment by patosullivan** [comment]
Been attempting to write the state transition this morning, will definitely need to pair with someone on it.

**Comment by patosullivan** [comment]
Apparently state transition is unnecessary, nevermind.

**Review by arthyn — APPROVED** [review]
lgtm, does the language class automatically provide a background?

**Comment by patosullivan** [comment]
> lgtm, does the language class automatically provide a background?

no, it's dark either way. I'll add white for dark mode now.

**Comment by patosullivan** [comment]
I just ended up using tailwind's invert utility and set a white background for dark mode:

image

**Pull request merged**
