### PR TITLE
unreads: cleanup bad marker placement, wrong counts, sorting

### PR DESCRIPTION
**Pull request by arthyn**
This fixes LAND-1274 and LAND-1292. Most of the bad behavior came from the fact that we were misusing `whom` in places mixing between flags and nests. This cleans that up to be consistent everywhere. 

Also fixes sorting by making sure that we correctly convert it to unix time for channels to match DMs so we compare well. Updates `last-read` time when we interact with a channel to ensure that the marker gets placed in the correct spot which was behavior we had previously, but went missing in refactor.

### CODE REVIEW

**Comment by arthyn** [comment]
This does not fix LAND-1251 I thought that was the same as what @jamesacklin had reported about talk sidebar being wrong. Will fix in a separate ticket.

**Comment by mrozanski** [comment]
Does this PR fix this? (I'm on your branch and still see it)

Screenshot 2023-11-30 at 11 16 09 AM

**Comment by mrozanski** [comment]
Testing this branch pointing to my main (migrated) ship, I get an exception when I start typing on the Leap text box.

Steps:

1. open Groups
2. [cmd + K]
3. Start typing

Error:

```
Error: Invalid nest
    at checkNest (https://localhost:3000/apps/groups/src/logic/utils.ts:58:13)
    at nestToFlag (https://localhost:3000/apps/groups/src/logic/utils.ts:65:3)
    at channelUnread (https://localhost:3000/apps/groups/src/logic/channel.ts:75:23)
    at https://localhost:3000/apps/groups/src/logic/channel.ts:90:14
    at scoreShipResult (https://localhost:3000/apps/groups/src/components/Leap/useLeap.tsx:148:11)
    at https://localhost:3000/apps/groups/src/components/Leap/useLeap.tsx:164:22
    at Array.filter (<anonymous>)
    at https://localhost:3000/apps/groups/src/components/Leap/useLeap.tsx:164:8
    at updateMemo (https://localhost:3000/apps/groups/node_modules/.vite/deps/chunk-GVSLPJMJ.js?v=3c4377af:12833:27)
    at Object.useMemo (https://localhost:3000/apps/groups/node_modules/.vite/deps/chunk-GVSLPJMJ.js?v=3c4377af:13349:24)
```

Screenshot 2023-11-30 at 1 00 01 PM

**Comment by mrozanski** [comment]
@arthyn For the newer on top (LAND-1292) does the ship sending the dm need to be on this branch as well as the one receiving?

I'm testing with my ship `~loclev-noctec`,hosted, on wannec, and locally `~rolwyl-litlut` (Mariano) on this branch.
Mariano still sees chats with older messages above loclev's

Screenshot 2023-11-30 at 5 38 05 PM

**Comment by mrozanski** [comment]
I can confirm that within each section (group channels and dms), chats appear in the order of those containing most recent messages first.
If that's the expected behavior then this is working as it should.

this is,

```

Talk sidebar - filter = All messages

[group chats]
most recent message
second most recent
...

[DM chats]
most recent message
second most recent
...

```

**Comment by arthyn** [comment]
@mrozanski I think you forgot to sync the group desk which would make the channels and DMs interleaved

**Comment by mrozanski** [comment]
You live and you learn.
That was it.

**Pull request merged**
