### PR TITLE
chat: fix initialization of 'new' in +di-abed-soft

### PR DESCRIPTION
**Pull request by jfranklin9000**
Addresses https://github.com/tloncorp/landscape-apps/issues/1890.

### CODE REVIEW

**Review by arthyn — CHANGES_REQUESTED** [review]
This solves many of the bad poke-acks but I still get one on a completely fresh ship. I think line 1634 should read:

```
  di-invited:di-core(ship s, dm d)
```

this seems to fix

**Comment by jfranklin9000** [comment]
I updated the PR.

I think this:
```
    =?  di-core  &(new !=(src our):bowl)
      di-invited:di-core(ship s, dm d)
    di-core(ship s, dm d)
```
could be:
```
    ?.  &(new !=(src our):bowl)
      di-core(ship s, dm d)
    di-invited:di-core(ship s, dm d)
```

**Comment by arthyn** [comment]
Yeah that's cleaner if you want to do that then we can merge

**Comment by jfranklin9000** [comment]
OK, done.

**Review by arthyn — APPROVED** [review]
lgtm, ty!

**Pull request merged**
