### PR TITLE
admin: reformat group settings

### LINKED ISSUE #1553: groups: host shows existing members as pending
**Describe the bug, optionally with screenshots**
Screenshot 2022-12-16 at 11 11 27 AM

Marisa is in the tlon group, but the host (dabben-larbet) shows her as pending.

### PR DESCRIPTION
**Pull request by jamesacklin**
Wholesale reboot of the Group Settings interface.

- Converts the interface to a tabbed-sidebar modal for large screens.
- Stacks the navigation and settings interfaces for small screens.
- Adjusts routes to consistently provide a background location for the modal.
- Makes the delete group name-check insensitive of special characters.
- Breaks the on-network invitation form out into its own component.
- Refactors the privacy selector.
- Virtualizes the pending list.
- Differentiates between Badge and AddBadge icons (and fixes the latter).
- Removes the header element of the Roles editor while editing a role.

A tour of Tlon Local and Tlon:

https://github.com/tloncorp/landscape-apps/assets/748181/9a17df48-9314-40cc-8ae4-8f4f445f59f8

Fixes tloncorp/landscape-apps#2348
Fixes tloncorp/landscape-apps#2486

Please note:

- Impacts #2466 in adjusting the privacy selector but nothing else
- Does not fix #1553 
- Does not reformat the basic "Group Info" form in #2348
- Does not implement group accent colors

### CODE REVIEW

**Comment by jamesacklin** [comment]
@patosullivan This messes with a lot of the group admin interfaces that you presumably changed in #2350. How would you prefer to coordinate?

**Comment by patosullivan** [comment]
> @patosullivan This messes with a lot of the group admin interfaces that you presumably changed in #2350. How would you prefer to coordinate?

After @arthyn's review mine should be good to go, how about we merge that first? I can push a commit to this branch to work out the merge conflicts if you like.

**Comment by jamesacklin** [comment]
I agree, let's merge your stuff to develop first. As long as your role components are relatively self-contained, it shouldn't be too hard to add a route/SidebarItem and drop them in.

**Review by patosullivan — CHANGES_REQUESTED** [review]
Overall it looks good, but there are two things:

- Normal group members can no longer access group info (biggest downside here imo is you can't see who is in the group with you).

- The close button in the modal seems like its should be in a different spot. The width of the cards within the main modal view apparently changes, which makes the X look kind of odd sitting where it does now IMO. I'll upload a video to show what I'm talking about.

**Comment by patosullivan** [comment]
https://github.com/tloncorp/landscape-apps/assets/1221094/bacc60e2-6c07-4eca-b360-06fa27a85408

**Comment by jamesacklin** [comment]
Agreed, thanks for the catch on non-admins.

> The close button in the modal seems like its should be in a different spot.

This is due to the scroll bar occupying some width (vs not when it's not needed) - @urcades do you have an interesting solution for where we should locate the close button? Or should it move over to acommodate the scroll bar?

**Comment by urcades** [comment]
> @urcades do you have an interesting solution for where we should locate the close button?

@jamesacklin providing an idea/solution for this problem by EOD

One other minor note I'll make is that when first assessing @patosullivan 's work on the roles paging animation, it felt good in the context of the video presented in the PR. When actually used (in my experience) it's a little disorienting and not yet fine-tuned enough to warrant its inclusion in the new settings ux. Secondly, no other sections appear to use this pattern, so it's a little jarring  to only surface this interaction in one place.

If it's easy to do in the context of this PR, I'd recommend we extract the animation from this experience until we can fine-tune its behavior or more generally apply it to other similar interfaces.

**Comment by jamesacklin** [comment]
@urcades Animation gone, will update the preview.

**Comment by urcades** [comment]
If we feel like we need to surface an explicit "x" to close out our modals, I think we should just situate them within an explicit space, such as this header (which is using the "Generic Channel Header" indigo component):

Screenshot 2023-05-30 at 5 34 03 PM

I personally feel like "tap out of modal" interaction is ubiquitous enough to warrant an implicit "ESC" key or "click outside of modal to close" to be acceptable, but I know there's no replacing explicit affordances like this. Might as well make it very obvious.

**Comment by jamesacklin** [comment]
@urcades and @patosullivan, updated with the latest

**Review by patosullivan — APPROVED** [review]
Looks good, I only found one thing that is annoying but probably not a blocker. The menu for the ship selector for group invites appears within the modal instead of on top of it:

image

We can probably fiddle with that separately since it involves the can of worms that is the ship selector.

**Pull request merged**
