### PR TITLE
Gallery: New posting interface and channel loading screen

### PR DESCRIPTION
**Pull request by latter-bolden**
Revamps the design for block input in Gallery channels (desktop and mobile). Supports drag and drop, paste, and previews for images and refs.

Drag and drop is disabled on mobile, and file upload silently ignores drag/paste if storage isn't enabled.

https://github.com/tloncorp/landscape-apps/assets/90741358/4f7215ae-2838-4f4b-987d-dedce4ad2c25

Fixes LAND-614
Fixes LAND-401

### CODE REVIEW

**Comment by jamesacklin** [comment]
Amazing work. Thank you!

Ran into something minor we might want to either document or refine later. When posting a link + more text, we get a link item with the text appended as expected in the title:

https://github.com/tloncorp/landscape-apps/assets/748181/d3291bfa-1443-44b7-b4e5-6c2f5f9876f2

Yet if you prepend the link with some text, you get a text block with a rich-formatted link (if you follow with a space):

https://github.com/tloncorp/landscape-apps/assets/748181/e3f3a13a-518a-46c8-859d-c4177795cd48

The exhibited behavior is sufficient for the time being and is actually somewhat predictable. I don't know that we need to do anything more or add any more UI to this. It's something to be aware of, though.

**Review by jamesacklin — CHANGES_REQUESTED** [review]
I  will, however, request that we handle the window-resize event in the drag-and-drop target for the entire gallery.

https://github.com/tloncorp/landscape-apps/assets/748181/2e9f5632-b650-408b-8491-bd8bf5806b13

**Review by patosullivan — APPROVED** [review]
Code looks good!

**Comment by latter-bolden** [comment]
I can't repro the drag target showing on resize. Let's merge and see if it crops up on binnec

**Pull request merged**
