### PR TITLE
mobile: add DMs to groups mobile

### PR DESCRIPTION
**Pull request by patosullivan**
this does not include adding DMs to desktop, but it could easily be added. this does not include the new icon treatment, but it could if we want it to.

fixes LAND-711

### CODE REVIEW

**Comment by jamesacklin** [comment]
@alecananian Can you point @patosullivan to the "isWebview" (or whatever) hook you mentioned yesterday? Might help feature-flag DMs-in-Groups in this case.

**Comment by alecananian** [comment]
Sure, if something should show in the app only, you can use the `isNativeApp` util flag: https://github.com/tloncorp/landscape-apps/blob/develop/ui/src/logic/native.ts

**Comment by patosullivan** [comment]
So we don't want this available if a user navigates to it in a mobile browser?

**Comment by patosullivan** [comment]
> Correct - if it's an easy-enough hook to use (and remove), we can enable when we feel the time is right.

fixed, chef

**Comment by jamesacklin** [comment]
Approved pending the merge conflict from the connectivity + saga stuff we merged today.

**Pull request merged**
