### PR TITLE
s3: add explicit, working CSP policy in index.html, workaround for safari

### PR DESCRIPTION
**Pull request by patosullivan**
Daniel is working on updating our CSP to add the `data` directive, which will allow apps like turf to work. This new policy breaks our image uploads due to a bug in safari. The workaround for us, that allows Daniel to update the CSP on hosting, is to apply the old hosting CSP policy to our app directly in the index.html.

### CODE REVIEW

**Comment by patosullivan** [comment]
Testing this with Daniel rn.

**Comment by mrozanski** [comment]
@dosullivan do you have any update? Could you guys test this?

**Comment by mrozanski** [comment]
@latter-bolden will. get this up on a moon for testing

**Comment by latter-bolden** [comment]
@dosullivan you can sync from `~dozped-mogtec`, both `%groups` and `%talk` have the CSP changes on there

**Comment by latter-bolden** [comment]
@dosullivan confirmed this PR in tandem with the hosting side change fix things for their use case. I also added support here for blob and data URLs for images & fonts.

We should talk through security implications together before we merge this.

**Comment by mrozanski** [comment]
Label: `Do not merge` can be removed once @latter-bolden 's concern is addressed

**Review by arthyn — APPROVED** [review]
lgtm

**Comment by mrozanski** [comment]
May fix https://linear.app/tlon/issue/LAND-1336
(test)

**Pull request merged**
