### PR TITLE
scroller: initial fix for short scrollers

### PR DESCRIPTION
**Pull request by dnbrwstr**
Working pr for fixing LAND-1040 and LAND-1041. The initial commit should fix most issues, but I'm still testing, and want to dig into the `hasLoadedNewest` flag, since that should probably have prevented these issues.

### CODE REVIEW

**Comment by jamesacklin** [comment]
Confirmed fixes 1040

**Comment by jamesacklin** [comment]
Confirmed fixes 1041

**Comment by dnbrwstr** [comment]
Also add a visible loader when loading at the top + fixed an issue with scroll tracking.

**Comment by patosullivan** [comment]
1041 still seems to be present:

https://github.com/tloncorp/landscape-apps/assets/1221094/2d4c9155-982c-4170-b8a4-70754eb04a9e

**Comment by dnbrwstr** [comment]
Ya, it's still present in the cases when you scroll up then down, but it should be fixed for the base case (just loading the page). I think the up and down issue has always been there? But I can work on a fix separately.

**Comment by jamesacklin** [comment]
I think this eases enough pain we can merge as-is and make a secondary case for scroll-up-down-then-post.

**Pull request merged**
