### PR TITLE
groups: restructuring of chat thread

### PR DESCRIPTION
**Pull request by rcrdlbl**
see: #1166 

Screen Shot 2022-11-20 at 2 23 08 AM

### CODE REVIEW

**Review by arthyn — CHANGES_REQUESTED** [review]
Just some small changes, pulled locally and worked well

**Review by urcades — APPROVED** [review]
Beautiful

**Comment by rcrdlbl** [comment]
@arthyn got these in!

**Review by arthyn — APPROVED** [review]
lgtm

**Pull request merged**
