### PR TITLE
groups: inline formatting fixes, code contrast in editor

### PR DESCRIPTION
**Pull request by rcrdlbl**
see: #1408, and part of #1444

I've taken a somewhat aggressive method of exiting out of bold/italic/etc that some people may find personally a little annoying, but IMO it's less annoying than the alternative (continuing to keep stuff immediately after the written text formatted)

### CODE REVIEW

**Comment by jamesacklin** [comment]
@patosullivan Mind pulling this down and giving it a go? I can't until later this morning.

**Review by patosullivan — CHANGES_REQUESTED** [review]
This doesn't seem to fix the issue described in #1391 (try inputting `ping https://tlon.io` with backticks surrounding it) and the fix for #1444 looks a bit wonky:

image

Notice how it breaks the padding around the input and overlaps with the file upload button.

**Comment by rcrdlbl** [comment]
@patosullivan sorry, that was my fault – I meant to mention #1408, i've done nothing to fix #1391. Currently playing with codeblock formatting.

**Comment by patosullivan** [comment]
I'm still seeing the first problem described here: "When I add a link to some text in Groups or Talk, everything I type afterwards is part of the hyperlink. The whole message afterwards is clickable, and if I delete the whole message with backspaces and type a new message, that message is hyperlinked."

**Comment by rcrdlbl** [comment]
@patosullivan 

https://user-images.githubusercontent.com/40729534/207949367-7cb12416-7461-43a5-9fe9-7f6e4e059214.mov

can you explain? links seem to properly escape for me

**Review by patosullivan — APPROVED** [review]
Maybe I just didn't pull earlier? LGTM

**Pull request merged**
